language: java
jdk:
  - oraclejdk8
os:
  - linux
sudo: required
env:
  global:
    - SC_BUILD_DIR=`pwd`
cache:
  directories:
    - .autoconf
    - $HOME/.m2
    - $HOME/.embedpostgresql
    - $HOME/.embedmysql
addons:
  apt:
    packages:
      - graphviz
script:
  - echo $SC_BUILD_DIR
  - mvn -Dcomplete clean package jacoco:report
after_success:
  - bash <(curl -s https://codecov.io/bash)

